language: node_js
node_js:
- '4.2'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libgif-dev
    - libjpeg8-dev
    - libpng12-dev
    - libglib2.0-dev
script:
- OUT_DIR=`pwd` TARGET=travis VERSION=`git describe --tags` ./build.sh
- rm -rf ./app ./ccv libccv*.tgz
env:
  global:
  - secure: AmoIIbrj2M1PcYgeiUHWmmYsfaJXaCabjEdnGdxSdS1gPYPEpeof/fhqQUnjpMpUzZ4ssVc2Z2xVHVevHgVsjKpvYCLEkkc81Bb6ANsq8HSIVRwvDwaD7ognV1tETcHNgWuIQQSzGl+qmPz9ldgFI1w0dq6mGHjYuBumtALYlvyOaeoR5Yzzh3vEUwwBCHcZVZeXT2w4OOHeSk3VA/3HOZLE/zXPIs4qrn/ZIYGd3GEN+GQKv1m8LDEXqx9nL7ZXQe6fy/ljMdvbylwDJ3dAuyhZGb80vOhOFYLEqFHfNAhDgtK6erDKu7c363exoRl3N86k0JchXZFNf9w1wuotkvC8fiIVjVLbfILErszTRbB+V+q5Ax24lzMXk7R7JX1ujWGzf4jVpGkkOOmo6v5XjS1d8hDR+eg1srdtx+PUJ3+15lEjzjnTzDUXfPV/SN9AfWykj3l8NPhhLcsvKywGrx4rGmdxzzQWv7yjeQH40Ue1GGWRdnI/1QyZtDf9Oo8xYlmPDIu0xIAQIOTH8XEHiycYvqvoZ2phhKHPVVLITyNF3WivUCTYtyLaMu2d3o/PxMdnMua/QKQOblmiJY8Vgjig69u4uLvnHzcf1k2Dm0DUtqc2tlBMI8nP8/jxdYpBsRWCm9vGvCD+WYJ8Pp4cs6WYS+GvkJvq1YZRUMTCeu8=
  - secure: LwwYi2NGFoEfeS6NUFQU98SIepM6UgTOrtkbszyHomzt5HTlKu6Kn28Dnf/4yrtOWJqHBxo5TpXHGqekPV+BLPxRQOCqrixv4vNFbxV/F4eokOuhhxmroZqzPyFTH/mKlmKb7WWdJTPd9aOFNIGymAJ9izi63xfZ7LQsrxGDVc/k0m3PzTf82F16tgJodKy44wjhkUHN/LB8ZBvf4B70jOgVTgQc4A0jsT7ezZ8tnV5KINc6EYG0QXnp3PULE2I2HZMuMARq2g5Y0DV9uDpq9Mt9FL7drjWomNwA+zBhF73wZdphMy0bK2jyrZVScGRjIJdS4AOZGiYATFi7QtjlPiF4gZ2kEnar/jCm9zKqQziPgid2iymUdW251E7qASFVbaulx9SPfNM4U2G8jizoRnGxK0wcBKLS6aZsBxVlHtdgK3GbwHs7O6cCcRzcnxpjO7Em8OFQM5PeLm2hFx8Gc6iVCXNyFZH6HZUxW28cQqKvDdJTBkvAVh8YZTbhhG6glRzP56C6wCtvDNyRPbVpG6jwX3+FFh5umMRDeyVDg2dVRsxpziVwWKrE8Y44luk2D0RFBQwN1PQs/9HwalhtQJun4rskq5NDHm7k+l0o0f0/ka4cfdt2XzNqRaBRfOWV6SQ/3Coh8AbyxHrNgRB9vPRdwqopOK9NhhVrWsy1a4k=
  - secure: mQUA1y4NzldTtfVw6QepV/5JgLoet9BpfNxPp2FGScn00lqSgWsfchwJWoOReP60XP3pRnieifTarRb8s3RlctEKmuHyUO3vWRnKT4jKGE/Yk5xBYDus26p06z2pDUvjmyLNS0433Wnn89txiwa6f2CW5Lmh8GCEMhz3g1hIYCmThmdVMWgF0dNS6xMRKazrTXgTfbOH5EwCNin7KCTiUlTfvUhFqAssNaVSXjaIe9PMLQDzYY1ThQ223LXkiKhGlNRlNedQ24JyfrlSjLxpVPKxat6cKjED6MKG78V4wHuwUHvy1xH5V03CeUQhmXYb5JbCgBLnrVJGEA76NWh6WMBYr9jEtL3a4sEt8a/utl9uuEIW5PgnXQWLQEga3KMC/ff2am/U5KYna0RYemQyynUK3CvxLdZe4JGPBuFE0GYI+eEaa5ifYVQm0VHKE6e6hWpzYf1YfmChsu8lDtqgkVZgT27h+1j8QGEq0fRnDMekQxNJf//UMdf9t2VeJt8kWZ6I68gzJ1aTjXe/iTHT0kMr8LmAT6cFokpwS+07V4KmOLaLsABjZI06ANYpxl81rees0fXg8WIkQzbC/BiTbPTI0cOsFDp/3Won4oi0O4t79T20rEOb6XW5CvKC/IKB/COsRFRKmbHUmKkyzrXcmxcBA3boy7frkoLA2kEw/pM=
deploy:
  provider: heroku
  app: buildpack-stage
  on:
    repo: the-grid/heroku-buildpack-ccv
    tags: true
  run:
  - TARGET=heroku VERSION=`git describe --tags` ./build.sh
  api_key:
    secure: bYdmHYkKgv5gpv6T9VMemtkMPHlgdfnDJ25RRU43Bn5yTa9/EqIcNhx1fI3nCo1jjStHU7TPAQPuCndNmYrDu/OpBj5Iok/10CpflfrZesV1rW2wqi+rkq/QyScZ3ZU2vRKuX975hP3LU5K3jeahc72wqF1oflxOz7fDzo/9Jsuv1Urc+l/ExTKXmbri/fKEpcY3muwjHoQjjVOuRRMe9KuvNtbcqod+T84Mpq3pUIqAx0nxwYmHpnqlNpaSwja0+j6UAsW6RE5Glniycrcl2iwNQ489/I8rkjBUwVA/jJfT9dRE2u3nELv7O0LVe0220E3oUXGIqvjRbXvYK3bPN7wwCaiHa+BBhu7Esj85mdsIHrzHBE2A7LqD6D+WGJjJoxHaAYxFO5CD/vFPF68VS1WdqcqC0Qy2bKBpgSYeO1iWmmqzCj8BECm55xHIATq9MYt0WroUAfMILZvU9vmLIC10dn67bYRiMwJHitZzbl5lSjgLqiTAGml6z9onCCLJBZyvwUU7nTD2Tu0MdVRYYOoT3tCLF6VhZvlZUGt9sB9iDMaw7adCBWsJ/DVu1sgRf1dQcb6yCy7vbtGiDXBzeiEbfaAvds+ei2UJR4b94yHg3K/qNLKj7o9+nFCIXbePJcmph4tr52hZb7/kgYEIg9kLjxgb9uiYBcsuaEhXqQQ=
