language: node_js
node_js:
- '4.2'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libgif-dev
    - libjpeg8-dev
    - libpng12-dev
    - libglib2.0-dev
script:
- OUT_DIR=`pwd` TARGET=travis VERSION=`git describe --tags` ./build.sh
- rm -rf ./app ./ccv libccv*.tgz
env:
  global:
  - secure: AmoIIbrj2M1PcYgeiUHWmmYsfaJXaCabjEdnGdxSdS1gPYPEpeof/fhqQUnjpMpUzZ4ssVc2Z2xVHVevHgVsjKpvYCLEkkc81Bb6ANsq8HSIVRwvDwaD7ognV1tETcHNgWuIQQSzGl+qmPz9ldgFI1w0dq6mGHjYuBumtALYlvyOaeoR5Yzzh3vEUwwBCHcZVZeXT2w4OOHeSk3VA/3HOZLE/zXPIs4qrn/ZIYGd3GEN+GQKv1m8LDEXqx9nL7ZXQe6fy/ljMdvbylwDJ3dAuyhZGb80vOhOFYLEqFHfNAhDgtK6erDKu7c363exoRl3N86k0JchXZFNf9w1wuotkvC8fiIVjVLbfILErszTRbB+V+q5Ax24lzMXk7R7JX1ujWGzf4jVpGkkOOmo6v5XjS1d8hDR+eg1srdtx+PUJ3+15lEjzjnTzDUXfPV/SN9AfWykj3l8NPhhLcsvKywGrx4rGmdxzzQWv7yjeQH40Ue1GGWRdnI/1QyZtDf9Oo8xYlmPDIu0xIAQIOTH8XEHiycYvqvoZ2phhKHPVVLITyNF3WivUCTYtyLaMu2d3o/PxMdnMua/QKQOblmiJY8Vgjig69u4uLvnHzcf1k2Dm0DUtqc2tlBMI8nP8/jxdYpBsRWCm9vGvCD+WYJ8Pp4cs6WYS+GvkJvq1YZRUMTCeu8=
  - secure: LwwYi2NGFoEfeS6NUFQU98SIepM6UgTOrtkbszyHomzt5HTlKu6Kn28Dnf/4yrtOWJqHBxo5TpXHGqekPV+BLPxRQOCqrixv4vNFbxV/F4eokOuhhxmroZqzPyFTH/mKlmKb7WWdJTPd9aOFNIGymAJ9izi63xfZ7LQsrxGDVc/k0m3PzTf82F16tgJodKy44wjhkUHN/LB8ZBvf4B70jOgVTgQc4A0jsT7ezZ8tnV5KINc6EYG0QXnp3PULE2I2HZMuMARq2g5Y0DV9uDpq9Mt9FL7drjWomNwA+zBhF73wZdphMy0bK2jyrZVScGRjIJdS4AOZGiYATFi7QtjlPiF4gZ2kEnar/jCm9zKqQziPgid2iymUdW251E7qASFVbaulx9SPfNM4U2G8jizoRnGxK0wcBKLS6aZsBxVlHtdgK3GbwHs7O6cCcRzcnxpjO7Em8OFQM5PeLm2hFx8Gc6iVCXNyFZH6HZUxW28cQqKvDdJTBkvAVh8YZTbhhG6glRzP56C6wCtvDNyRPbVpG6jwX3+FFh5umMRDeyVDg2dVRsxpziVwWKrE8Y44luk2D0RFBQwN1PQs/9HwalhtQJun4rskq5NDHm7k+l0o0f0/ka4cfdt2XzNqRaBRfOWV6SQ/3Coh8AbyxHrNgRB9vPRdwqopOK9NhhVrWsy1a4k=
  - secure: mQUA1y4NzldTtfVw6QepV/5JgLoet9BpfNxPp2FGScn00lqSgWsfchwJWoOReP60XP3pRnieifTarRb8s3RlctEKmuHyUO3vWRnKT4jKGE/Yk5xBYDus26p06z2pDUvjmyLNS0433Wnn89txiwa6f2CW5Lmh8GCEMhz3g1hIYCmThmdVMWgF0dNS6xMRKazrTXgTfbOH5EwCNin7KCTiUlTfvUhFqAssNaVSXjaIe9PMLQDzYY1ThQ223LXkiKhGlNRlNedQ24JyfrlSjLxpVPKxat6cKjED6MKG78V4wHuwUHvy1xH5V03CeUQhmXYb5JbCgBLnrVJGEA76NWh6WMBYr9jEtL3a4sEt8a/utl9uuEIW5PgnXQWLQEga3KMC/ff2am/U5KYna0RYemQyynUK3CvxLdZe4JGPBuFE0GYI+eEaa5ifYVQm0VHKE6e6hWpzYf1YfmChsu8lDtqgkVZgT27h+1j8QGEq0fRnDMekQxNJf//UMdf9t2VeJt8kWZ6I68gzJ1aTjXe/iTHT0kMr8LmAT6cFokpwS+07V4KmOLaLsABjZI06ANYpxl81rees0fXg8WIkQzbC/BiTbPTI0cOsFDp/3Won4oi0O4t79T20rEOb6XW5CvKC/IKB/COsRFRKmbHUmKkyzrXcmxcBA3boy7frkoLA2kEw/pM=
deploy:
  provider: heroku
  api_key:
    secure: zAkG4M5ZS7Ar1IyUvhD5bGqXgrm1H/nhIeaHcyCAWR9Fm3ZleqdOfvuqEotiz/bcJPlrnrWsrFHL4Vxvl9Ia4/g7vUrMvyeIjG9oV8g6z+xvfQ0/sB+UMTuMJEKxLz7VXIbsEQisxv8o/H+tuKcX5P96cW/lgWyGWq0agjT0wwNduBKkLnJfILYbngKrZL9LMfneiUbzAf/LFk+dAfVvTHRD/Oe66tSrj+bcnW/buhnBZ8nlskVkYScvOwBhw0IWpgBEBT76hqH2kEcdHZJr4qD7MZR4bWgRXtS4snX7REWeeqm0aDFe7sFZY6IKBWYi2rCyhcCN8fwdkMAERSL1ACC3Fg5vbcA6dSQWE+sHmKiesGvl+o4JPADnddF6FZ9mZBFeoeTnxltgutwfcJVEpMcVnkQh/l7vilmKcOczmveSy0Y3zN2UuFeF0+s2ToJQfeM9MuwxDY/5+Kje6tDe4SgnnR8WlY51PYWFxMkK6reDugPsEAjwsyPtAhs7IVc2JmYUfwp2uuxNYax4wrQzYE22cefySwG4tVeUAflvWD+QRMFR2mrdPxp/d+k8RxOXoWW1w6btykZdb4FYVjume3BLCB/xdNmX/xXxyAquQeRMRePtrCwIV5LTRjAv9GlJaep+n45l2kp+v0H+5bS98UpZndtrnf/RKuwZ8rQoOyk=
  app: imgflo-dependencies14
  on:
    repo: jonnor/heroku-buildpack-ccv
    tags: true
  run:
  - TARGET=heroku VERSION=`git describe --tags` ./build.sh
