language: node_js
node_js:
- '4.2'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libgif-dev
    - libjpeg8-dev
    - libpng12-dev
    - libglib2.0-dev
script:
- OUT_DIR=`pwd` TARGET=travis VERSION=`git describe --tags` ./build.sh
env:
  global:
  - secure: KORfxiPT9MTJcjgRltPJ+irmPmh5veOmrYI+c2LJA8eJHQdStOCaefER8Of/j0axmLIbnlrZYkS7+91HZKhVU1G62tt/f7WMijSytPXrU8NLUhOQrLNGaQPT4akV5vMU4s7hzXNK2hw+ZPezgKBhyCiiw5Ex/0aFL1tPmbEhyODMb2l3zkYurbpvDOBmJKvdgRYLKkH0O8CuuhoyoSAvjdanofZT34SZWzJan6dViJllkLWNI8S0QHqXEb1ISQma6/Mvcjz4D5t0RJaKy0RAxCHwfnCX5fzZhhqwhnRKRBKmQMh87E5DKRDKLdqZf4WBzzqq7D7Pf5jBVIhsPvZaEYpKktPKSNCbX8JFw+Un7tpC8QyuA3rrOv1efRstra7Mpvdm0tLuUMdRhwCfQIIwBWdwd0Nsvw8z26yNUY0h/0gTilaTJca8/imihon6mHH4hsi4eYtnqeSatcq47K0Sz8fpTlay4v8TemD/rqiSW0mKKN6jHRTAFquDu2X+CxIjmZ/ShCCWhjpEQGkJTvicvfm+CJDvYciBXfxCPaju8jqgcTdcrx0b71OHOj2rvRDDZZ0QDTovBspUG1u8OQKrZarejo7EhxV3VjqPSFnpoZz97igKdbxfWzTBLgcWq5/IWRDIR4kFupbI9cU7VMDTBLD4gi2kndLL/waXMRDic6s=
  - secure: MYxlfgs6JLSS8GD592tjXvZoXoQlVuyeHAV9Jjj0XMSlgMuNnas+70rodivp5dqgclwt7G1d8d6fajcqs+qwshSAMUccKSDyoV1OyVygrC7ko5pmszDMcA/qMCa8z88c7qnpSJs8FOJgmP3uRbcg3naGkXH2RYCVpfEMkckJsiWpoU4RwMgCX5Sr2SDPihNKBhIpl2h5xPCZ8jBuF2/xY7NVECkHmAF+PLyr8ApSxsjEIwD2cf4an2IlevzEvppuS+Mfy4+sAIKX8DFwuM1KOu5YIVMYCooDDAInOZqpGPD7ez1e56+Y152a+qwOiRdDvBb/ElayC9YlRrGZDz7hE4bcmUkTpjHEy9TKQA5sQ+PJmTn/K951+OQ0UNhktmCvan4/jYjhG/0xJ6GyBDipnR5dUfGeUF6hzrUMlLzJD/JJ5JVxYgfEpufcz3Qnn+P18b0fOl308YHKRaydD8C9OGNDg1MoYTwQUCTdROr/olkG2qA3nwO8uemReZpME1aHUUXMWsoOtqDWGLLpInLfkw1H43mVN2U9+6POsCYy44itIctEazWByQ+HFbowDhMrrqlfPOCOWr3pT5SMOmLpnpRizwRBcQtJ3L9iU5Oewe0pafvj1wOyphn/YChfKStLQZkQ6hDieV+eUeQHxmhTGc6x5g88zwm4WY85lPRc7ww=
  - secure: kvmA/9b2xTyo9IEgsOF/LNBu7ycK770POALmfS7ORoTTHPwbXvR4PvSG142rIqhjDyzQ8iaAwdbwOW8VSEAW3+dIb0tJARMWNZULiBlEeEJv5jeiOLR2X05XsP+uYkOeq1le1g5OdYYj2+t3RN/lDNg/lrUfDGr65ZSM44MZKkQVNDna618JDX8DJEnxCdMx7wY0rVqXOipTGiWvhKC5TJ1GIdPxzNDznqliGK5qMcPJl10F9lMdHh+0JTVN32AIYRwNAu6ta8TyytOPZnXy177jNV9Oh6BkDKjWy9cFikJ472kXVVqQ0pimLzcYo6Lx2huELa+9i3R0o76FiYPi3oRvl7l6v7KY4l3QjtR8UikaJP66JOVXz6AY7JvJVwKx3oDVuTKHv9DvyXEDID6WAiVJ9P2FMkkIehiOmVkxK4HtiSmGTd7Im5uxWQUDrfMT6gD4uzBqkD2kbj5rMQNtTdHBNtgSRpbjcHR4pX2LlAmB1+Xjlrok6NEIkAdL6S8KUnKOTtI0oHEQW54BvR82M3Y5nDMF71srtc967dQsqwUO2jkSUsqL/SVsSSb1PbtZg9ZphFPTVVloXp40ErvxO76GHCdhegSzQBnegbaNHCLggzfeTKshZYQeYzGZ7nsUyWnm75EwbUm6ftkwxZxt0jyVA9hL6+dxCYwdNzej0Mk=
deploy:
  provider: heroku
  api_key:
    secure: zAkG4M5ZS7Ar1IyUvhD5bGqXgrm1H/nhIeaHcyCAWR9Fm3ZleqdOfvuqEotiz/bcJPlrnrWsrFHL4Vxvl9Ia4/g7vUrMvyeIjG9oV8g6z+xvfQ0/sB+UMTuMJEKxLz7VXIbsEQisxv8o/H+tuKcX5P96cW/lgWyGWq0agjT0wwNduBKkLnJfILYbngKrZL9LMfneiUbzAf/LFk+dAfVvTHRD/Oe66tSrj+bcnW/buhnBZ8nlskVkYScvOwBhw0IWpgBEBT76hqH2kEcdHZJr4qD7MZR4bWgRXtS4snX7REWeeqm0aDFe7sFZY6IKBWYi2rCyhcCN8fwdkMAERSL1ACC3Fg5vbcA6dSQWE+sHmKiesGvl+o4JPADnddF6FZ9mZBFeoeTnxltgutwfcJVEpMcVnkQh/l7vilmKcOczmveSy0Y3zN2UuFeF0+s2ToJQfeM9MuwxDY/5+Kje6tDe4SgnnR8WlY51PYWFxMkK6reDugPsEAjwsyPtAhs7IVc2JmYUfwp2uuxNYax4wrQzYE22cefySwG4tVeUAflvWD+QRMFR2mrdPxp/d+k8RxOXoWW1w6btykZdb4FYVjume3BLCB/xdNmX/xXxyAquQeRMRePtrCwIV5LTRjAv9GlJaep+n45l2kp+v0H+5bS98UpZndtrnf/RKuwZ8rQoOyk=
  app: imgflo-dependencies14
  on:
    repo: jonnor/heroku-buildpack-ccv
    tags: true
  run:
  - TARGET=heroku VERSION=`git describe --tags` ./build.sh
